CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team1 VARCHAR(100) NOT NULL,
    team2 VARCHAR(100) NOT NULL,
    status VARCHAR(32) NOT NULL,
    top_k INT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    points DOUBLE PRECISION NOT NULL DEFAULT 0,
    CONSTRAINT uk_user_teams_game_user UNIQUE (game_id, user_id),
    CONSTRAINT fk_user_teams_game FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_teams_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_team_players (
    user_team_id BIGINT NOT NULL,
    player_id INT NOT NULL,
    PRIMARY KEY (user_team_id, player_id),
    CONSTRAINT fk_user_team_players_user_team
        FOREIGN KEY (user_team_id) REFERENCES user_teams (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ball_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    batsman INT NOT NULL,
    bowler INT NOT NULL,
    score INT NOT NULL,
    CONSTRAINT fk_ball_events_game FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE
);
